fix compilation error(s): -Wincompatible-pointer-types
reported by gcc 15

buffer_put.c:75:20: error: passing argument 1 of‘allwrite’ from incompatible pointer type [-Wincompatible-pointer-types]
buffer_put.c:50:5: error: conflicting types for ‘buffer_put’; have‘int(buffer *, char *, unsigned int)’
...

both read & write are used in buffer init, so remove const (for write)
from prototype