fix undesired compilation error(s) of feature test
If don't fix, the feature test will generate undesired .h which will be used
in later compilation, some will cause build failed.

see *.h{1,2} for details, run following cmd to see difference:
  diff -uprN <(more *.h1|sed 's:\.h1$:.h:g') <(more *.h2|sed 's:\.h2$:.h:g')

found by using clang 18 with CFLAGS: -Wall

link of debian's patches is: https://salsa.debian.org/debian/runit/-/tree/master/debian/patches
  0029-fix-ftbfs-with-gcc14.patch

chkshsgr.c trycpp.c trypoll.c tryshsgr.c tryulong64.c:
  error: call to undeclared function '...'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  functions are: _exit, exit, getgroups, printf, setgroups

tryflock.c trysgact.c trysgprm.c trywaitp.c:
  error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]